/**
 * adsStyles — Estilos compartidos para landing pages de Google Ads.
 * Extraídos de TutoriaAcademica (la landing modelo, ya aprobable).
 * Úsalos en cualquier landing nueva que cuelgue de AdsLandingLayout.
 */
export const styles = {
  /* MINI HEADER */
  miniHeader: {
    background: '#fff',
    borderBottom: '1px solid #e2e8f0',
    padding: '14px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  miniHeaderLogo: { height: '38px', width: 'auto' },
  miniHeaderCta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: '#25d366',
    color: '#fff',
    padding: '10px 20px',
    borderRadius: '10px',
    fontSize: '0.9rem',
    fontWeight: 700,
    textDecoration: 'none',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  /* MINI FOOTER */
  miniFooter: {
    background: '#1a1a2e',
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
    padding: '32px 24px',
    fontSize: '0.88rem',
    lineHeight: 1.7,
  },
  miniFooterBrand: { color: '#fff', fontWeight: 700, fontSize: '1.05rem', marginBottom: '8px' },
  miniFooterLink: { color: 'rgba(255,255,255,0.6)', textDecoration: 'none', margin: '0 10px', fontSize: '0.82rem' },
  page: {
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    color: '#1a1a2e',
    overflowX: 'hidden',
    background: '#fff',
  },
  /* HERO */
  hero: {
    background: 'linear-gradient(160deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    color: '#fff',
    padding: '100px 24px 80px',
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  heroBg: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    background: 'radial-gradient(circle at 20% 50%, rgba(79,70,229,0.3) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(37,211,102,0.15) 0%, transparent 40%)',
    pointerEvents: 'none',
  },
  heroContent: { maxWidth: '820px', margin: '0 auto', position: 'relative', zIndex: 1 },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(255,193,7,0.12)',
    border: '1px solid rgba(255,193,7,0.35)',
    color: '#ffc107',
    fontSize: '0.88rem',
    fontWeight: 600,
    padding: '8px 20px',
    borderRadius: '50px',
    marginBottom: '24px',
    backdropFilter: 'blur(10px)',
  },
  heroTitle: {
    fontSize: 'clamp(2rem, 5vw, 3.2rem)',
    fontWeight: 800,
    lineHeight: 1.12,
    marginBottom: '20px',
    letterSpacing: '-0.03em',
  },
  heroGradientText: {
    background: 'linear-gradient(135deg, #fff 0%, #a5b4fc 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroSub: {
    fontSize: 'clamp(1.05rem, 2vw, 1.2rem)',
    lineHeight: 1.65,
    opacity: 0.9,
    maxWidth: '640px',
    margin: '0 auto 32px',
  },
  heroCtas: { display: 'flex', gap: '16px', justifyContent: 'center', flexWrap: 'wrap', marginBottom: '32px' },
  ctaPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    background: 'linear-gradient(135deg, #25d366 0%, #128C7E 100%)',
    color: '#fff',
    padding: '16px 32px',
    borderRadius: '14px',
    fontSize: '1.08rem',
    fontWeight: 700,
    textDecoration: 'none',
    transition: 'all 0.3s ease',
    boxShadow: '0 8px 25px rgba(37,211,102,0.35)',
    border: 'none',
    cursor: 'pointer',
  },
  ctaSecondary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(255,255,255,0.08)',
    border: '1px solid rgba(255,255,255,0.25)',
    color: '#fff',
    padding: '16px 28px',
    borderRadius: '14px',
    fontSize: '1rem',
    fontWeight: 600,
    textDecoration: 'none',
    transition: 'all 0.3s ease',
    backdropFilter: 'blur(10px)',
    cursor: 'pointer',
  },
  trustRow: { display: 'flex', gap: '28px', justifyContent: 'center', flexWrap: 'wrap', fontSize: '0.88rem', fontWeight: 500, opacity: 0.85 },
  trustItem: { display: 'inline-flex', alignItems: 'center', gap: '6px' },
  /* SECTIONS */
  section: { padding: '80px 24px', maxWidth: '1140px', margin: '0 auto' },
  sectionAlt: { padding: '80px 24px', background: 'linear-gradient(180deg, #f8f9ff 0%, #eef1ff 100%)' },
  sectionInner: { maxWidth: '1140px', margin: '0 auto' },
  sectionTitle: {
    fontSize: 'clamp(1.6rem, 3.5vw, 2.3rem)',
    fontWeight: 800,
    textAlign: 'center',
    marginBottom: '12px',
    color: '#1a1a2e',
    letterSpacing: '-0.02em',
  },
  sectionSub: { textAlign: 'center', maxWidth: '680px', margin: '0 auto 48px', color: '#64748b', fontSize: '1.08rem', lineHeight: 1.65 },
  /* FEATURES */
  featuresGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px' },
  featureCard: {
    background: '#fff',
    border: '1px solid #e2e8f0',
    borderRadius: '20px',
    padding: '32px 28px',
    transition: 'all 0.3s ease',
    cursor: 'default',
    position: 'relative',
    overflow: 'hidden',
  },
  featureIconWrap: {
    width: '56px',
    height: '56px',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '18px',
    fontSize: '1.5rem',
  },
  featureTitle: { fontSize: '1.1rem', fontWeight: 700, marginBottom: '10px', color: '#1a1a2e' },
  featureDesc: { fontSize: '0.95rem', color: '#64748b', lineHeight: 1.6, margin: 0 },
  /* STEPS */
  stepsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '32px', position: 'relative' },
  step: { textAlign: 'center', padding: '8px', position: 'relative' },
  stepNum: {
    width: '60px',
    height: '60px',
    background: 'linear-gradient(135deg, #4F46E5 0%, #7c3aed 100%)',
    color: '#fff',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    fontWeight: 800,
    margin: '0 auto 18px',
    boxShadow: '0 8px 20px rgba(79,70,229,0.25)',
  },
  stepTitle: { fontSize: '1.08rem', fontWeight: 700, marginBottom: '10px', color: '#1a1a2e' },
  stepDesc: { fontSize: '0.92rem', color: '#64748b', lineHeight: 1.6, margin: 0 },
  /* PRICING */
  pricingGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '28px', alignItems: 'stretch' },
  priceCard: {
    background: '#fff',
    borderRadius: '24px',
    padding: '36px 28px 32px',
    textAlign: 'center',
    position: 'relative',
    border: '2px solid #e2e8f0',
    transition: 'all 0.3s ease',
    display: 'flex',
    flexDirection: 'column',
  },
  priceCardFeatured: {
    background: 'linear-gradient(180deg, #fafafe 0%, #f0edff 100%)',
    borderColor: '#4F46E5',
    boxShadow: '0 12px 40px rgba(79,70,229,0.15)',
    transform: 'scale(1.02)',
  },
  priceBadge: {
    position: 'absolute',
    top: '-14px',
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'linear-gradient(135deg, #4F46E5 0%, #7c3aed 100%)',
    color: '#fff',
    padding: '6px 22px',
    borderRadius: '50px',
    fontSize: '0.8rem',
    fontWeight: 700,
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap',
  },
  priceLevel: { fontSize: '1.15rem', fontWeight: 700, color: '#64748b', marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.06em' },
  priceAmount: { fontSize: '2.8rem', fontWeight: 800, color: '#1a1a2e', lineHeight: 1 },
  priceUnit: { fontSize: '0.95rem', color: '#94a3b8', fontWeight: 500, marginBottom: '24px', display: 'block', marginTop: '4px' },
  priceList: { listStyle: 'none', padding: 0, margin: '0 0 28px', textAlign: 'left', flex: 1 },
  priceListItem: { display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 0', fontSize: '0.94rem', color: '#475569', borderBottom: '1px solid #f1f5f9' },
  checkIcon: { color: '#25d366', flexShrink: 0, fontSize: '0.85rem' },
  priceBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    padding: '14px 24px',
    borderRadius: '14px',
    fontSize: '1rem',
    fontWeight: 700,
    textDecoration: 'none',
    transition: 'all 0.3s ease',
    width: '100%',
    boxSizing: 'border-box',
  },
  /* TESTIMONIALS */
  testimonialsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px' },
  testimonialCard: { background: '#fff', borderRadius: '20px', padding: '28px', border: '1px solid #e2e8f0', position: 'relative' },
  testimonialStars: { color: '#ffc107', display: 'flex', gap: '2px', marginBottom: '14px', fontSize: '0.95rem' },
  testimonialText: { fontSize: '0.98rem', lineHeight: 1.65, color: '#475569', marginBottom: '18px', fontStyle: 'italic' },
  testimonialAuthor: { display: 'flex', alignItems: 'center', gap: '12px' },
  authorAvatar: { width: '44px', height: '44px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, fontSize: '1rem', color: '#fff' },
  authorName: { fontSize: '0.95rem', fontWeight: 700, color: '#1a1a2e' },
  authorRole: { fontSize: '0.82rem', color: '#94a3b8' },
  /* FAQ */
  faqList: { maxWidth: '780px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '12px' },
  faqItem: { background: '#fff', border: '1px solid #e2e8f0', borderRadius: '16px', overflow: 'hidden', transition: 'all 0.2s ease' },
  faqQuestion: {
    width: '100%',
    padding: '20px 24px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '1rem',
    fontWeight: 600,
    color: '#1a1a2e',
    textAlign: 'left',
    fontFamily: 'inherit',
  },
  faqAnswer: { padding: '0 24px 20px', fontSize: '0.95rem', color: '#64748b', lineHeight: 1.65 },
  faqChevron: { transition: 'transform 0.3s ease', color: '#4F46E5', flexShrink: 0, marginLeft: '12px' },
  /* FINAL CTA */
  finalCta: {
    background: 'linear-gradient(160deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    color: '#fff',
    textAlign: 'center',
    padding: '80px 24px',
    position: 'relative',
    overflow: 'hidden',
  },
  finalCtaBg: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    background: 'radial-gradient(circle at 50% 50%, rgba(79,70,229,0.2) 0%, transparent 60%)',
    pointerEvents: 'none',
  },
  finalCtaIcon: { fontSize: '3rem', marginBottom: '20px', opacity: 0.9 },
  finalCtaTitle: { fontSize: 'clamp(1.6rem, 3.5vw, 2.3rem)', fontWeight: 800, marginBottom: '14px' },
  finalCtaSub: { maxWidth: '560px', margin: '0 auto 28px', opacity: 0.88, fontSize: '1.08rem', lineHeight: 1.6 },
};

/* Colores rotativos para tarjetas de beneficios */
export const featureColors = [
  { bg: '#eef2ff', color: '#4F46E5' },
  { bg: '#ecfdf5', color: '#059669' },
  { bg: '#fef3c7', color: '#d97706' },
  { bg: '#fce7f3', color: '#db2777' },
  { bg: '#e0f2fe', color: '#0284c7' },
  { bg: '#f3e8ff', color: '#7c3aed' },
];
